version: "3"
services:
    db:
        container_name: mongodb
        image: mongo
        restart: always
        ports: 
            - 27017:27017
        volumes:
            - ./mongo:/server/mongo
        #command: bundle exec thin -p 3000
    server:
        build: ./server
        container_name: server
        ports:
            - 8888:8888
        volumes:
            - ./server/src:/server/src
        links:
            - db
    web:
        build: ./front
        container_name: front
        ports:
            - 8889:8889
        volumes:
            - ./front/public:/front/public
            - ./front/src:/front/src
volumes:
    mongodb:
    data-volume: